In [95]:
import networkx as nx
import ast
import numpy as np

In [74]:
# g = nx.read_gml('testCinfExport.gml')

In [75]:
# nx.to_dict_of_dicts(g)

In [82]:
def convert_gml(fileName): #GridToolsTBD exports to a text file - this grabs it and converts the edges back to lists
                           #super inneficient - should convert to pickle file system or something
    g = nx.read_gml(fileName)
    for edge in g.edges:
        g[edge[0]][edge[1]]['weight'] = ast.literal_eval(g[edge[0]][edge[1]]['weight'])
        g[edge[0]][edge[1]]['weight'] = g[edge[0]][edge[1]]['weight'][0]+g[edge[0]][edge[1]]['weight'][1] #end result is edge weights as list of
                                                                                                          #multiplicities [U1,U2...,Un,V1,...,Vn]
    return g

def construct_cinf(g, size = -1): #Construct CFKinf complex from graph data - essentially just changing weights to polynomials
                                  #Only works for grid diagrams *not* Latin Squares
    if size == -1:
        size = len(g.get_edge_data(list(g.edges())[0][0],list(g.edges())[0][1])['weight'])  #kind of a mess - just turning the edges
    n = size/2                                                                              #into a list and checking the length of
                                                                                            #the weight of the first edge
    F,Vars = cinf_coeff(n)
    sageG = DiGraph()
    for edge in g.edges:
        start = edge[0]
        end = edge[1]
        poly = F(1)
        i = 0
        for entry in g[edge[0]][edge[1]]['weight']:
            poly = poly*(Vars[i])**entry
            i = i + 1
#        g[start][end]['weight'] = poly
        sageG.add_edge(start,end,poly)
    return sageG
        
def cinf_coeff(size):
    n = size
    preF = LaurentPolynomialRing(GF(2), 'U', n) #F[Ui+-] which we'll then pair up with the Vi
    preF.inject_variables()                     #Telling Sage we have Ui's as variables
    Vars = preF.gens()                          #storing the variables in a list - not currently implemented anywhere
    F = LaurentPolynomialRing(preF, 'V', n)     #Takes our preF (F[Ui+-]) and adjoins Vi
    F.inject_variables()                        #F only thinks it has Vi as variables, we tell Sage about it
    Vars = Vars + F.gens()
    return F,Vars

def find_one(targetlist): #Searches a list for first 1 - will be used for reduction
#     print("searching for 1 in" + str(targetlist))
    if 1 in list(targetlist):
#         print("found 1 in the list at" + str(list(targetlist).index(1)))
        return list(targetlist).index(1)
    return -1

def find_col_with_one(matrix, startc=0):
    endc = len(matrix[0])
    print(str(endc))
    for n in range(startc, endc):
        search_result = find_one(matrix[:][n])
        if search_result != -1:
            return (search_result, n)
    return (-1, -1)


def reduction_remap(matrix, row, col):
    n = len(matrix[0])
    range1 = range_skip_entry(n, row)
#     print("searching through " + str(range1))
    for count, target_row in enumerate(range1):
        entry = matrix[target_row][col]
        if entry != 0:
#             print("doing row addition with row" + str(row))
#             print("and count" + str(count))
#             print("and entry (multiple)" + str(entry))
            my_row_add(matrix, row, target_row, entry)
    return matrix

def row_col_del(matrix, loc):
    newrange = list(range(len(matrix[0])))
    del newrange[loc]
    return matrix[newrange,newrange]

def range_skip_entry(n, skip):
    u = []
    for i in range(0, skip):
        u.append(i)
    for j in range(skip+1, n):
        u.append(j)
    return u

def reduction(matrix):
    col, row = find_col_with_one(matrix)
#     print("reducing around entry " +str(row) + "," +str(col))
    if col == -1:
        print("completed reduction")
        print(matrix)
        print (type(matrix))
        return matrix
    print("reduction in progress")
    remapped_matrix = reduction_remap(matrix, row, col)
    if row < col:
        remapped_matrix = row_col_del(remapped_matrix, col)
        remapped_matrix = row_col_del(remapped_matrix, row)
    else:
        remapped_matrix = row_col_del(remapped_matrix, row)
        remapped_matrix = row_col_del(remapped_matrix, col)
    return reduction(remapped_matrix)
    
def my_row_add(matrix, row, targetrow, multiple):
    n = len(matrix[0])
    for i in range(n):
        current_src = matrix[row][i]
        if current_src != 0:
#             print("adding copies times " + str(current_src))
#             print("multiple" + str(multiple))
#             print("target entry " + str(matrix[targetrow][i]))
            matrix[targetrow,i] = matrix[targetrow][i] + multiple*current_src
#         print(matrix)
    return matrix
        

In [57]:
thering = cinf_coeff(3)

Defining U0, U1, U2
Defining V0, V1, V2


In [100]:
g = convert_gml('testCinfExport.gml')
sageG = construct_cinf(g)
dictg = nx.to_dict_of_dicts(g)
newg = DiGraph()
#graphs.graph_input.from_dict_of_dicts(dictg, weighted = True)
newg
myf = sageG.weighted_adjacency_matrix()

Defining U0, U1, U2, U3, U4, U5
Defining V0, V1, V2, V3, V4, V5


In [101]:
myf

720 x 720 sparse matrix over Multivariate Laurent Polynomial Ring in V0, V1, V2, V3, V4, V5 over Multivariate Laurent Polynomial Ring in U0, U1, U2, U3, U4, U5 over Finite Field of size 2 (use the '.str()' method to see the entries)

In [102]:
trefred = reduction(myf)

720
reduction in progress
718
reduction in progress
716
reduction in progress
714
reduction in progress
712
reduction in progress
710
reduction in progress
708
reduction in progress
706
reduction in progress
704
reduction in progress
702
reduction in progress
700
reduction in progress
698
reduction in progress
696
reduction in progress
694
reduction in progress
692
reduction in progress
690
reduction in progress
688
reduction in progress
686
reduction in progress
684
reduction in progress
682
reduction in progress
680
reduction in progress
678
reduction in progress
676
reduction in progress
674
reduction in progress
672
reduction in progress
670
reduction in progress
668
reduction in progress
666
reduction in progress
664
reduction in progress
662
reduction in progress
660
reduction in progress
658
reduction in progress
656
reduction in progress
654
reduction in progress
652
reduction in progress
650
reduction in progress
648
reduction in progress
646
reduction in progress
644
reductio

In [96]:
idk = np.array(trefred)

In [99]:
idk

array([[0, V2, V1, ..., 0, 0, 0],
       [U4, 0, 0, ..., 0, 0, 0],
       [U3, 0, 0, ..., 0, 0, V3],
       ...,
       [0, 0, 0, ..., 0, 0, U2],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, U0 + U3, ..., V2, V0, 0]], dtype=object)

In [98]:
nx.Graph(idk)

NetworkXError: Input is not a correct numpy matrix or array.

In [80]:
myf

120 x 120 sparse matrix over Multivariate Laurent Polynomial Ring in V0, V1, V2, V3, V4 over Multivariate Laurent Polynomial Ring in U0, U1, U2, U3, U4 over Finite Field of size 2 (use the '.str()' method to see the entries)

In [61]:
testmat = matrix([[1,0,U1],[V0,1,V2],[U0,U1,V2]])
testmat

[ 1  0 U1]
[V0  1 V2]
[U0 U1 V2]

In [45]:
my_row_add(testmat, 0, 1, V0)

adding copies times 1
multipleV0
target entry V0
[ 1  0 U1]
[ 0  1 V2]
[U0 U1 V2]
[ 1  0 U1]
[ 0  1 V2]
[U0 U1 V2]
adding copies times U1
multipleV0
target entry V2
[         1          0         U1]
[         0          1 U1*V0 + V2]
[        U0         U1         V2]


[         1          0         U1]
[         0          1 U1*V0 + V2]
[        U0         U1         V2]

In [62]:
reduction_remap(testmat,0,0)

searching through [1, 2]
doing row addition with row0
and count0
and entry (multiple)V0
adding copies times 1
multipleV0
target entry V0
[ 1  0 U1]
[ 0  1 V2]
[U0 U1 V2]
[ 1  0 U1]
[ 0  1 V2]
[U0 U1 V2]
adding copies times U1
multipleV0
target entry V2
[         1          0         U1]
[         0          1 U1*V0 + V2]
[        U0         U1         V2]
doing row addition with row0
and count1
and entry (multiple)U0
adding copies times 1
multipleU0
target entry U0
[         1          0         U1]
[         0          1 U1*V0 + V2]
[         0         U1         V2]
[         1          0         U1]
[         0          1 U1*V0 + V2]
[         0         U1         V2]
adding copies times U1
multipleU0
target entry V2
[         1          0         U1]
[         0          1 U1*V0 + V2]
[         0         U1 V2 + U0*U1]


[         1          0         U1]
[         0          1 U1*V0 + V2]
[         0         U1 V2 + U0*U1]

In [64]:
test = reduction(matrix([[0,1,U1],[V0,0,V2],[U0,U1,V2]]))

3
searching for 1 in(0, 1, U1)
found 1 in the list at1
reducing around entry 0,1
reduction in progress
searching through [1, 2]
doing row addition with row0
and count1
and entry (multiple)U1
[ 0  1 U1]
[V0  0 V2]
[U0 U1 V2]
adding copies times 1
multipleU1
target entry U1
[ 0  1 U1]
[V0  0 V2]
[U0  0 V2]
adding copies times U1
multipleU1
target entry V2
[        0         1        U1]
[       V0         0        V2]
[       U0         0 V2 + U1^2]
1
searching for 1 in(V2 + U1^2)
reducing around entry -1,-1
completed reduction
[V2 + U1^2]
<class 'sage.matrix.matrix_generic_dense.Matrix_generic_dense'>


In [107]:
myf.add_multiple_of_row(1,2,U1)

In [108]:
myf

[              0              U1              U0               0               0              U2]
[     V0 + U1*V2               0               0      U1*U2 + U0 U1^2*V0 + U2*V1               0]
[             V2               0               0              U2           U1*V0               0]
[              0              V2              V1               0               0              V0]
[              0               1               1               0               0               1]
[             V1               0               0              U1           U0*V2               0]

In [109]:
1 in GF(3)

True

In [110]:
1 in thering

False

In [111]:
myf[0,1] in thering

False

In [112]:
find_col_with_one(myf)

6
searching for 1 in(0, U1, U0, 0, 0, U2)
searching for 1 in(V0 + U1*V2, 0, 0, U1*U2 + U0, U1^2*V0 + U2*V1, 0)
searching for 1 in(V2, 0, 0, U2, U1*V0, 0)
searching for 1 in(0, V2, V1, 0, 0, V0)
searching for 1 in(0, 1, 1, 0, 0, 1)
found 1 in the list at1


(1, 4)

In [116]:
newmat = reduction(myf)

6
searching for 1 in(0, U1, U0, 0, 0, U2)
searching for 1 in(V0, 0, 0, U0, U2*V1, 0)
searching for 1 in(V2, 0, 0, U2, U1*V0, 0)
searching for 1 in(0, V2, V1, 0, 0, V0)
searching for 1 in(0, 1, 1, 0, 0, 1)
found 1 in the list at1
reducing around entry 4,1
reduction in progress
searching through [0, 1, 2, 3, 5]
doing row addition with row4
and count0
and entry (multiple)V0
[    0    U1    U0     0     0    U2]
[   V0     0     0    U0 U2*V1     0]
[   V2     0     0    U2 U1*V0     0]
[    0    V2    V1     0     0    V0]
[    0     1     1     0     0     1]
[   V1     0     0    U1 U0*V2     0]
adding copies times 1
multipleV0
target entry U1
[      0 V0 + U1      U0       0       0      U2]
[     V0       0       0      U0   U2*V1       0]
[     V2       0       0      U2   U1*V0       0]
[      0      V2      V1       0       0      V0]
[      0       1       1       0       0       1]
[     V1       0       0      U1   U0*V2       0]
adding copies times 1
multipleV0
target entry U0


In [145]:
print(newmat)

[     0 U0 + 1      0 U2 + 1]
[    V2      0     U2      0]
[     0 V1 + 1      0 V0 + 1]
[    V1      0     U1      0]


In [59]:
myf

[        0        U1        U0         0         0        U2]
[       V0         0         0        U0     U2*V1         0]
[       V2         0         0        U2     U1*V0         0]
[        0        V2        V1         0         0        V0]
[        0  U1^2 + 1 U0*U1 + 1         0         0 U1*U2 + 1]
[       V1         0         0        U1     U0*V2         0]

In [58]:
print(newmat)

None


In [32]:
range_skip_entry(5,2)

[0, 1, 3, 4]

In [33]:
g.get_edge_data(list(g.edges())[0][0],list(g.edges())[0][1])['weight']

[1, 0, 0, 0, 0, 0]

In [98]:
preF = LaurentPolynomialRing(GF(2), 4, ('w'))
preF.inject_variables()
F = LaurentPolynomialRing(preF,4,'z')
F.inject_variables()
F.gens()[0]

Defining w0, w1, w2, w3
Defining z0, z1, z2, z3


z0

In [165]:
preF = LaurentPolynomialRing(GF(2), 'U', 3)
preF.inject_variables()
F = LaurentPolynomialRing(GF(2), 'V', 3)
F.inject_variables()

Defining U0, U1, U2
Defining V0, V1, V2


In [16]:
F

Multivariate Laurent Polynomial Ring in U, V over Finite Field of size 2

In [ ]:
#OLD CODE

# def reduce_around(M, position): 
# #M isa matrix and position is a pair [a,b] where a 1 is located
# #function does Gauss-Jordan-ish elimination on that column and in a symmetric way to the entry's row
#     a,b = position
#     #First step is to use the row to cancel the other entries, then we'll do a symmetric cancellation on
#     #the columns as well
#     column = M[:][b]
#     for index, entry in enumerate(column):
#         if ((index != 0) and (index != a) and (entry != 0)):
#             M.add_multiple_of_row(index, entry, a)
#     for index, entry in enumerate(column):
#         if ((index != 0) and (index != a) and (entry != 0)):
#             M.add_multiple_of_col(index, entry, b)
#     #Now we'll repeat the process but with the row entries
#     row = M[a][:]
#     for index, entry in enumerate(row):
#         if ((index != 0) and (index != b) and (entry != 0)):
#             M.add_multiple_of_col(index, entry, b)
#     for index, entry in enumerate(column):
#         if ((index != 0) and (index != b) and (entry != 0)):
#             M.add_multiple_of_row(index, entry, a)
#     return

# def hom_reduction(adj_mat):
#     M = adj_mat
#     row_position = 0
#     for row in M:
#         check, column_position = row_count(row)
#         if row_count(check[0]) > 1:
#             reduce_around(M, row_position, column_position)
#         row_position = position + 1